### PR TITLE
Some suggested revisions

### PR DESCRIPTION
**Pull request by tcn33**
Some suggestions for accuracy, as well as compliance with GitHub's [Acceptable Use Policies](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies).

### CODE REVIEW

**Comment by pelmered** [comment]
LGTM!

**Review by vinnysgreen — APPROVED** [review]

**Comment by navjotjsingh** [comment]
This is a pull request I can definitely get behind.

**Comment by vagelisp** [comment]
Looking good !

**Review by navjotjsingh — APPROVED** [review]

**Review by singatias — APPROVED** [review]
This is a 100x programmer innovation, I love it!

**Comment by marpstar** [comment]
May I suggest that we add a counter of developers who'll never use WordPress again? 🙋🏻‍♂️

**Review by rodvilla — APPROVED** [review]

**Review by therobbiedavis — APPROVED** [review]
👍 No notes!

**Comment by singatias** [comment]
@wordpressenginetracker why would you close this PR? The community is here to help, please do not throw away the hard work @tcn33 ...

**Review by soulseekah — COMMENTED** [review]
LGTM

**Review by asirota — COMMENTED** [review]
Looks pretty much perfect. Good coding standards too.

**Pull request closed without merging**
